### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Mat40** [iLLeniumStudios/fivem-loki-logging#1]
Hi when i run install.sh i obtain this error : 
`
Release "cert-manager" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource ServiceAccount "cert-manager-cainjector" in namespace "cert-manager": Get "https://127.0.0.1:6443/api/v1/namespaces/cert-manager/serviceaccounts/cert-manager-cainjector": dial tcp 127.0.0.1:6443: connect: connection refused
`

**Comment by TheiLLeniumStudios** [comment]
Hi @Mat40 
Use discord to get support on this. Create a new post in the support channel
https://discord.illenium.dev
