### ISSUE TITLE
You could've said it removes Apache2 from 80 port and puts Nginx instead now everything is fucked

### ISSUE THREAD

**Issue by NeyZzO** [iLLeniumStudios/fivem-loki-logging#3]

**Comment by NeyZzO** [comment]
Now tell me how to solve the issue, when I go to my domain name, nothing works instead I have a beautiful blank page of NGINX telling me it cannot find the page. Plus what's better nginx doesn't exist on my machine. So what do I do ??

**Comment by NeyZzO** [comment]
If you want the domain: https://redv.fr/
Oh no sorry your thing fucked everything up now it's http://redv.fr

**Comment by davefl67** [comment]
It does say in the FAQ:
**Q:** Can I run this on an existing Linux VM / VPS?
**A:** You can but there are no guarantees if it will work or not. I will NOT be responsible if your VPS is affected while attempting to install it. It is highly recommended to setup a new VM / VPS just for this setup.
