### ISSUE TITLE
I understand Discord is preferred for support, but...

### ISSUE THREAD

**Issue by davefl67** [iLLeniumStudios/fivem-loki-logging#4]
Your Ansible script for CAPTCHA seems to be fucked
![image](https://github.com/iLLeniumStudios/fivem-loki-logging/assets/107778859/bf1150ad-2366-4b1c-b515-575336042435)

My Discord is [@davefl67](https://discordapp.com/users/136827471801614336)

**Comment by TheiLLeniumStudios** [comment]
I'm aware of it. Should be fixed soon
