### ISSUE TITLE
Installing into a Docker container

### ISSUE THREAD

**Issue by davefl67** [iLLeniumStudios/fivem-loki-logging#5]
1. I do not use or know Kubernetes
2. I do not have another "fresh" VM or VPS available

Any ideas on the best way to install into a container? I was thinking of just an empty container running Debian and just use the command line from inside that container. Does that sound like the way to go?

**Comment by TheiLLeniumStudios** [comment]
Its not possible to run this script within a container. It doesn't work like that. There are probably other solutions out there that run Loki and Grafana directly on containers but I do not have a guide for you for that unfortunately
